# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds, achieves and uploads ipa to TestFlight"
  lane :testflight do
    ENV["FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD"] = "obhe-ryoj-trfs-rcou"
    increment_build_number(xcodeproj: “YoungSt.xcodeproj”)

    gym(
      clean: true,
      output_directory: "./build"
    )
    
    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
